//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team1.TruckLoadPlanning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderList
    {
        public int ID { get; set; }
        public string TNNo { get; set; }
        public string CaseNo { get; set; }
        public Nullable<int> CaseLength { get; set; }
        public Nullable<int> CaseWidth { get; set; }
        public Nullable<int> CaseHeight { get; set; }
        public Nullable<double> Volume { get; set; }
        public Nullable<double> Qty { get; set; }
        public string Address { get; set; }
        public string PackageMaterial { get; set; }
        public string Coordinate { get; set; }
        public string TruckType { get; set; }
        public string TruckNo { get; set; }
        public string Dimension { get; set; }
    }
}
