//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team1.TruckLoadPlanning.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TruckSummary
    {
        public string TruckType { get; set; }
        public int TruckNo { get; set; }
        public double OptimizationPrecentage { get; set; }
        public string Coordinate { get; set; }
        public Nullable<int> DimensionX { get; set; }
        public Nullable<int> DimensionY { get; set; }
        public Nullable<int> DimensionZ { get; set; }
    }
}
